### ISSUE TITLE
Feedback Windows installation

### ISSUE THREAD

**Issue by teunbrand** [clauswilke/sinab#10]
Hi Claus,

I saw you were gathering feedback on twitter for the windows installation of sinab, so here is my experience.
The installation of sinab itself went fine, it was installing Rust that required a small bit of adapting.

Specifically, because the instructions didn't specify whether the commands are to be run in Windows PowerShell or the command prompt, I tried the PowerShell.  To install Rust, I had to change the following line:

```
set PATH=%PATH%;\%USERPROFILE%\.cargo\bin
```

to this:

```
$env:PATH += ";{path\to\my\profile}\.cargo\bin"
```

Wherein `{path\to\my\profile}` is my user directory. After that, I could install sinab from github and run the examples in the readme without any problem.

**Comment by clauswilke** [comment]
Can you use `%USERPROFILE%` in place of `{path\to\my\profile}` in the PowerShell?

**Comment by teunbrand** [comment]
No I don't think that would work because when I try that it appends `%USERPROFILE%` verbatim instead of substituting the user directory.

**Comment by clauswilke** [comment]
Maybe it's `$env:USERPROFILE`? https://devblogs.microsoft.com/scripting/powertip-use-powershell-to-find-user-profile-path/

**Comment by teunbrand** [comment]
Yep that would work. In the meantime I tried the same at the command prompt and that didn't require any change from the instructions. So I would guess that specifying that these commands should be run at the command prompt would resolve the kink in the cable that I had.

**Comment by teunbrand** [comment]
Instructions are very clear now, I'll go on and close this issue!
