### ISSUE TITLE
Compiling on Windows is currently broken

### ISSUE THREAD

**Issue by clauswilke** [clauswilke/sinab#13]
Compiling with Windows currently [errors out:](https://ci.appveyor.com/project/clauswilke/sinab)

```
error: linking with `x86_64-w64-mingw32-gcc` failed: exit code: 1
...
  = note: C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgcc_eh
          collect2.exe: error: ld returned 1 exit status
          

error: aborting due to previous error

error: could not compile `getrandom`
```

This may be related to the release of rustc 1.48.0, see here: https://users.rust-lang.org/t/announcing-rust-1-48-0/51677/6

**Comment by clauswilke** [comment]
Here is an old issue that is possibly related: https://github.com/rust-lang/rust/issues/41607

**Comment by clauswilke** [comment]
@yutannihilation Do you happen to have any idea how to approach/fix this build problem on Windows? I suspect it'll eventually hit the extendr project as well.

**Comment by yutannihilation** [comment]
No idea. Curious... Do you think this is an issue specific to getrandom crate?

> ``error: could not compile `getrandom` ``

**Comment by clauswilke** [comment]
No, I don't think so:
https://github.com/rust-lang/rust/issues/41607#issuecomment-299505769

**Comment by yutannihilation** [comment]
Okay, it seems time to boot my old Windows again...

**Comment by clauswilke** [comment]
If you could look into it, that would be great! I saw a post somewhere saying it was something about a path issue (it uses `x86_64-w64-mingw32/bin/ld.exe` instead of the linker shipped with Rust), but I can't find that post anymore and I don't have Windows to test.

**Comment by yutannihilation** [comment]
Before I jump into the hell of Windows Updates, I tried Windows runner on GitHub Actions CI, and it seems there's no compilation error happens. Curious...

https://github.com/yutannihilation/sinab/runs/1480737543

diff: https://github.com/clauswilke/sinab/compare/master...yutannihilation:master

**Comment by clauswilke** [comment]
That's good to know. Maybe it is a path issue after all. Could you turn this into a PR? And what does `override: true` do?

**Comment by yutannihilation** [comment]
Sure, I'll create a PR.

The document says `override` is to

> Set installed toolchain as an override for the current directory
https://github.com/actions-rs/toolchain#inputs

But, I didn't know about the details, I just copied this from [the instruction on hellorust](https://github.com/r-rust/hellorust/#github-actions), which was recently added. I guess this is for ensuring the runner uses the intended toolchain even when there's already another Rust toolchain installed, so this probably doesn't matter in usual cases.

**Comment by yutannihilation** [comment]
Confirmed it works without `override`.

https://github.com/yutannihilation/sinab/runs/1483598627

**Comment by clauswilke** [comment]
Closing this as it does work on GH Actions. Probably something is not quite right in the Appveyor setup, but there's nothing fundamental that is broken with the code.
